root: ../data/exp/follow
num_min_agents: 100
num_max_agents: 1000
num_interval_agents: 100
congestion_levels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 20
  - 25
time_limit_sec: 60
time_limit_sec_force: 90
seed_start: 1
seed_end: 1
scen: scen-warehouse

solver_options:
  - "--checkpoints-duration"
  - "1"

maps:
  - warehouse-20-40-10-2-2
